FROM golang:latest as builder

RUN mkdir /app
ADD . /app/
WORKDIR /app
RUN  GOOS=linux go build o -o poolService .

FROM alpine
WORKDIR /app/
COPY --from=builder /app/poolService .
CMD ["/app/poolService"]